### ISSUE TITLE
Add Spring I/O

### ISSUE THREAD

**Issue by salmar** [fvcproductions/diversify-me#6]
Spring I/O 2019 has introduced diversity sponsorships. Could you please add it to the list?

Event name: Spring I/O 2019
Dates: 16-17 May 2019
Place: Barcelona, Spain
Event page: https://2019.springio.net
Diversity scholarships: https://2019.springio.net/diversity-scholarships

**Comment by FrancesCoronel** [comment]
Looks great - will add to the list 👍
